# Generated by Django 4.2.19 on 2025-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
